// koajs-react-mongodb-todolist/client/src/List.js
import React, { Component } from 'react'
import { getList, addToList, deleteItem, updateItem } from './ListFunctions'

class List extends Component {
  constructor() {
    super()
    this.state = {
      id: '',
      term: '',
      editDisabled: false,
      items: []
    }

    this.onSubmit = this.onSubmit.bind(this)
    this.onChange = this.onChange.bind(this)
  }

  componentDidMount() {
    this.getAll()
  }

  onChange = event => {
    this.setState({ term: event.target.value, editDisabled: 'disabled' })
  }

  getAll = () => {
    getList().then(data => {
      this.setState(
        {
          term: '',
          items: [...data]
        },
        () => {
          console.log(this.state.items)
        }
      )
    })
  }

  onSubmit = e => {
    e.preventDefault()
    addToList(this.state.term).then(() => {
      this.getAll()
    })
    this.setState({ editDisabled: false })
  }

  onUpdate = e => {
    e.preventDefault()
    updateItem(this.state.term, this.state.id).then(() => {
      this.getAll()
    })
    this.setState({ editDisabled: false })
  }

  onEdit = (item, itemid, e) => {
    e.preventDefault()
    this.setState({
      id: itemid,
      term: item
    })
  }

  onDelete = (val, e) => {
    e.preventDefault()
    deleteItem(val).then(() => {
      this.getAll()
    })
  }

  render() {
    return (
      <div className="col-md-12">
        <form onSubmit={this.onSubmit}>
          <div className="form-group">
            <label htmlFor="exampleInputEmail1">Task Name</label>
            <div className="row">
              <div className="col-md-9">
                <input
                  type="text"
                  className="form-control"
                  id="exampleInputEmail1"
                  value={this.state.term || ''}
                  onChange={this.onChange.bind(this)}
                />
              </div>
              <div className="col-md-2">
                <button
                  className="btn btn-primary"
                  onClick={this.onUpdate.bind(this)}
                >
                  Update
                </button>
              </div>
            </div>
          </div>
          <button
            type="submit"
            onClick={this.onSubmit.bind(this)}
            className="btn btn-success btn-block"
          >
            Submit
          </button>
        </form>
        <table className="table">
          <tbody>
            {this.state.items.map((item, index) => (
              <tr key={index}>
                <td className="text-left">{item.task_name}</td>
                <td className="text-right">
                  <button
                    href=""
                    className="btn btn-info mr-1"
                    disabled={this.state.editDisabled}
                    onClick={this.onEdit.bind(this, item.task_name, item._id)}
                  >
                    Edit
                  </button>
                  <button
                    href=""
                    className="btn btn-danger"
                    onClick={this.onDelete.bind(this, item._id)}
                  >
                    Delete
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )
  }
}

export default List

// koajs-vuejs-mongodb-todolist/client/src/components/List.vue
<template>
  <div class="hello">
    <div id="todo-list-example" class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <h1 class="text-center">TODO List App</h1>
          <form v-on:submit.prevent="addNewTask">
            <label for="tasknameinput">Task Name</label>
            <input
              v-model="taskname"
              id="tasknameinput"
              class="form-control"
              placeholder="Add New Task"
            />
            <button
              v-if="this.isEdit == false"
              type="submit"
              class="btn btn-success btn-block  mt-3"
            >
              Submit
            </button>
            <button
              v-else
              type="button"
              v-on:click="updateTask()"
              class="btn btn-primary btn-block  mt-3"
            >
              Update
            </button>
          </form>

          <table class="table">
            <tr
              v-for="(todo) in todos"
              v-bind:key="todo._id"
              v-bind:task_name="todo.task_name"
            >
              <td class="text-left">{{ todo.task_name }}</td>
              <td class="text-right">
                <button
                  v-on:click="editTask(todo.task_name, todo._id)"
                  class=" btn btn-info "
                >
                  Edit
                </button>
                <button
                  v-on:click="deleteTask(todo._id)"
                  class=" btn btn-danger "
                >
                  Delete
                </button>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  data () {
    return {
      todos: [],
      id: '',
      taskname: '',
      isEdit: false
    }
  },
  mounted () {
    this.getTasks()
  },
  methods: {
    getTasks () {
      axios({ method: 'GET', url: '/api/tasks' }).then(
        result => {
          console.log(result.data)
          this.todos = result.data
        },
        error => {
          console.error(error)
        }
      )
    },
    addNewTask () {
      axios
        .post('/api/task', { task_name: this.taskname })
        .then(res => {
          this.taskname = ''
          this.getTasks()
          console.log(res)
        })
        .catch(err => {
          console.log(err)
        })
    },

    editTask (taskname, id) {
      this.id = id
      this.taskname = taskname
      this.isEdit = true
    },

    updateTask () {
      axios
        .put(`/api/task/${this.id}`, { task_name: this.taskname })
        .then(res => {
          this.taskname = ''
          this.isEdit = false
          this.getTasks()
          console.log(res)
        })
        .catch(err => {
          console.log(err)
        })
    },

    deleteTask (id) {
      axios
        .delete(`/api/task/${id}`)
        .then(res => {
          this.taskname = ''
          this.getTasks()
          console.log(res)
        })
        .catch(err => {
          console.log(err)
        })
    }
  }
}
</script>
